//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public equipos()
        {
            this.movimientos_enquipos = new HashSet<movimientos_enquipos>();
        }
    
        public int id_equipo { get; set; }
        public Nullable<int> id_programacion { get; set; }
        public Nullable<int> id_marca { get; set; }
        public Nullable<int> id_modelo { get; set; }
        public string codigo { get; set; }
        public Nullable<decimal> precio_eq { get; set; }
        public Nullable<System.DateTime> fecha_cad { get; set; }
        public string tipo_equipo { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimientos_enquipos> movimientos_enquipos { get; set; }
        public virtual marcas marcas { get; set; }
        public virtual modelos modelos { get; set; }
        public virtual programacion programacion { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
