//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimientos_enquipos
    {
        public int id_mov { get; set; }
        public Nullable<int> id_equipo { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<int> id_encabezado { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_departamento { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual departamentos departamentos { get; set; }
        public virtual empleados empleados { get; set; }
        public virtual encabezado_movimientos encabezado_movimientos { get; set; }
        public virtual equipos equipos { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
